language: objective-c

notifications:
  slack: devlucky:0AP12qjjfc2Zxc0s9yo1cQQm

env:
  global:
    - WORKSPACE=Kakapo.xcworkspace
    - COVERAGE=NO

podfile: Podfile

osx_image: xcode10.2

matrix:
  include:
    - env: DESTINATION="arch=x86_64" SCHEME=macOS SDK="macosx10.14"
    - env: DESTINATION="OS=12.2,name=Apple TV 4K (at 1080p)" SCHEME=tvOS SDK="appletvsimulator12.2"
    - env: DESTINATION="OS=12.2,name=iPhone X" SCHEME=iOS SDK="iphonesimulator12.2" COVERAGE=YES
      before_install:
        - gem install danger
        - gem install danger-swiftlint
      before_script:
        - danger
        - pod lib lint --quick
      after_success:
        - bash <(curl -s https://codecov.io/bash) -J 'Kakapo'

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace $WORKSPACE -scheme Kakapo\ $SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ENABLE_TESTABILITY=YES -enableCodeCoverage $COVERAGE test | xcpretty;
